version: '3'
services:
  mysql:
    image: 'mysql:latest'
    ports:
      - '8080:3306'
    volumes:
      - database-data:/var/lib/mysql
    env_file:
      - database.env
    networks:
      - mysql

volumes:
  database-data: 
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /media/starlord/D/Ashish/Projects/mysql/data

networks:
  mysql:
       driver: bridge